# Generated by Django 2.2.9 on 2019-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='protein_sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('protein_id', models.IntegerField(blank=True, null=True, verbose_name='Id')),
                ('protein_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('protein_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Class')),
                ('protein_taxo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Taxo')),
                ('protein_fasta', models.TextField(blank=True, null=True, verbose_name='Fasta')),
                ('protein_uniprot_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Protein UniProt Id')),
                ('protein_SWISSMODEL_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Protein SWISS-MODEL Id')),
            ],
            options={
                'verbose_name': 'Protein Sequence',
                'verbose_name_plural': 'Protein Sequences',
                'db_table': 'protein_sequence',
            },
        ),
    ]
