# Generated by Django 2.2.9 on 2019-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein_sequence',
            name='protein_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Id'),
        ),
    ]
