# Generated by Django 2.2.9 on 2019-12-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0002_auto_20191227_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein_sequence',
            name='protein_MODBASE_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protein MODBASE Id'),
        ),
    ]
