# Generated by Django 2.2.9 on 2019-12-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0003_protein_sequence_protein_modbase_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('request_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Request Type')),
                ('request_detail', models.TextField(blank=True, null=True, verbose_name='Request Detail')),
                ('requester_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Request Email')),
                ('request_status', models.TextField(blank=True, null=True, verbose_name='Request Status')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'job_request',
            },
        ),
    ]
