# Generated by Django 2.2.9 on 2019-12-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0004_request_queue'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request_queue',
            table='request_queue',
        ),
    ]
