# Generated by Django 2.2.9 on 2020-01-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0005_auto_20191230_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene_miRNA_cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('cluster_id', models.IntegerField(verbose_name='cluster Id')),
                ('gene_id', models.CharField(max_length=255, verbose_name='gene_ID')),
                ('miRNA_id', models.CharField(max_length=255, verbose_name='miRNA_ID')),
            ],
            options={
                'db_table': 'gene_miRNA_cluster',
                'verbose_name_plural': 'Gene miRNA Clusters',
                'verbose_name': 'Gene miRNA Cluster',
            },
        ),
        migrations.CreateModel(
            name='gene_miRNA_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('gene_id', models.CharField(max_length=255, verbose_name='gene_ID')),
                ('miRNA_id', models.CharField(max_length=255, verbose_name='miRNA_ID')),
            ],
            options={
                'db_table': 'gene_miRNA_mapping',
                'verbose_name_plural': 'Gene miRNA Mappings',
                'verbose_name': 'Gene miRNA Mapping',
            },
        ),
        migrations.CreateModel(
            name='gene_sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('gene_id', models.CharField(max_length=255, verbose_name='ID')),
                ('gene_fasta', models.TextField(blank=True, null=True, verbose_name='Fasta')),
            ],
            options={
                'db_table': 'gene_sequence',
                'verbose_name_plural': 'Gene Sequences',
                'verbose_name': 'Gene Sequence',
            },
        ),
        migrations.CreateModel(
            name='miRNA_sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('miRNA_id', models.CharField(max_length=255, verbose_name='ID')),
                ('miRNA_fasta', models.TextField(blank=True, null=True, verbose_name='Fasta')),
            ],
            options={
                'db_table': 'miRNA_sequence',
                'verbose_name_plural': 'miRNA Sequences',
                'verbose_name': 'miRNA Sequence',
            },
        ),
    ]
