# Generated by Django 2.2.9 on 2020-01-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0006_gene_mirna_cluster_gene_mirna_mapping_gene_sequence_mirna_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene_mirna_cluster',
            name='gene_id',
        ),
        migrations.RemoveField(
            model_name='gene_mirna_cluster',
            name='miRNA_id',
        ),
        migrations.AddField(
            model_name='gene_mirna_cluster',
            name='gene_miRNA_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gene_miRNA_ID'),
        ),
        migrations.AddField(
            model_name='gene_mirna_cluster',
            name='gene_miRNA_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gene_miRNA_type'),
        ),
    ]
