# Generated by Django 2.2.9 on 2020-01-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0007_auto_20200105_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_mirna_cluster',
            name='gene_miRNA_id',
            field=models.CharField(max_length=255, verbose_name='gene_miRNA_ID'),
        ),
        migrations.AlterField(
            model_name='gene_mirna_cluster',
            name='gene_miRNA_type',
            field=models.CharField(max_length=255, verbose_name='gene_miRNA_type'),
        ),
    ]
