# Generated by Django 2.2.9 on 2020-01-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0009_auto_20200105_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mirna_sequence',
            options={'verbose_name': 'miRNA_sequence', 'verbose_name_plural': 'miRNA_sequences'},
        ),
        migrations.AddField(
            model_name='gene_sequence',
            name='ncbi_gene_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NCBI_gene_ID'),
        ),
    ]
