# Generated by Django 2.2.9 on 2020-01-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0012_auto_20200111_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_mirna_cluster',
            name='cluster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_clusters', to='bio_app.clusters'),
        ),
    ]
