# Generated by Django 2.2.9 on 2020-01-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0013_auto_20200111_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='cluster_id',
            field=models.CharField(max_length=255, verbose_name='cluster Id'),
        ),
    ]
