# Generated by Django 2.2.9 on 2020-01-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0014_auto_20200111_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene_mirna_cluster',
            name='cluster_id',
            field=models.IntegerField(verbose_name='cluster Id'),
        ),
        migrations.RenameModel(
            old_name='clusters',
            new_name='Cluster',
        ),
        migrations.CreateModel(
            name='Cluster_miRNA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('miRNA_id', models.CharField(max_length=255, verbose_name='miRNA_ID')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_app.Cluster')),
            ],
            options={
                'unique_together': {('cluster_id', 'miRNA_id')},
                'verbose_name_plural': 'clusters_miRNAs',
                'verbose_name': 'clusters_miRNA',
                'db_table': 'cluster_miRNA',
            },
        ),
        migrations.CreateModel(
            name='Cluster_Gene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('gene_id', models.CharField(max_length=255, verbose_name='gene_ID')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_app.Cluster')),
            ],
            options={
                'unique_together': {('cluster_id', 'gene_id')},
                'verbose_name_plural': 'clusters_genes',
                'verbose_name': 'clusters_gene',
                'db_table': 'cluster_gene',
            },
        ),
    ]
