# Generated by Django 2.2.9 on 2020-01-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0015_auto_20200111_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster_gene',
            old_name='cluster_id',
            new_name='cluster',
        ),
        migrations.RenameField(
            model_name='cluster_mirna',
            old_name='cluster_id',
            new_name='cluster',
        ),
        migrations.AlterUniqueTogether(
            name='cluster_gene',
            unique_together={('cluster', 'gene_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cluster_mirna',
            unique_together={('cluster', 'miRNA_id')},
        ),
    ]
