# Generated by Django 2.2.9 on 2020-01-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0016_auto_20200111_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster_gene',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cluster_mirna',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
