# Generated by Django 2.2.9 on 2020-01-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0017_auto_20200111_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ('name',), 'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterModelOptions(
            name='cluster_gene',
            options={'ordering': ('gene_id',), 'verbose_name': 'clusters_gene', 'verbose_name_plural': 'clusters_genes'},
        ),
        migrations.AlterModelOptions(
            name='cluster_mirna',
            options={'ordering': ('miRNA_id',), 'verbose_name': 'clusters_miRNA', 'verbose_name_plural': 'clusters_miRNAs'},
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='cluster_id',
        ),
        migrations.AddField(
            model_name='cluster',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
